// User
export const ERROR_RECEIVE_USER = 'ERROR_RECEIVE_USER';
export const ERROR_SIGN_OUT = 'ERROR_SIGN_OUT';
export const RECEIVE_USER = 'RECEIVE_USER';
export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';
export const REQUEST_USER = 'REQUEST_USER';
export const SUCCESS_SIGN_OUT = 'SUCCESS_SIGN_OUT';
